### ISSUE TITLE
Theme support?

### ISSUE THREAD

**Issue by FireSon** [loogn/bulmarazor#4]
Hi,
Impressed with your work!!
Is there a possibility for theming support? I noticed you almost added all Bulma extensions very nice! Is there a reason you did not add the IconPicker?
Thanks!

**Comment by loogn** [comment]
Hello there
You can modify the theme of BulmaRazor just like the theme of Bulma, [see here](https://bulmarazor.loogn.net/docs/overview/theme) .

Regarding the IconPicker extension, I opened its [webpage](https://wikiki.github.io/form/iconpicker/) but couldn't see the effect, so it was not implemented ,Did I find the wrong place?

**Comment by FireSon** [comment]
Thanks for the quick response!!
It was a bit difficult to read the theme page for me :-) since I am from Europe, but I understand it is possible which is very nice! Would it be possible to switch between 'dark mode' and 'normal' mode by pressing a button? Or do I need to select a different css?

The IconPicker example does not work, although the example code to open the picker seems to be:
```
<input type="text" id="iconPicker" data-action="iconPicker" value="fa fa-icon fa-star" />
<p class="help">Click on icon to open the iconPicker.</p>
```

**Comment by loogn** [comment]
You're welcome!
To modify the theme, you need to write your own CSS.
Here I briefly describe:
1. clone the style repository
```git clone git@github.com:loogn/bulmarazor-theme.git```
2. Install dependencies
```npm install```
3. Modify mybulma.sass
For specific variables, please refer to [bulma official website](https://bulma.io/documentation/customize/variables/).
4. Build a custom style
```npm run buildmy```
5. Replace the style file
Copy the css/mybulma.min.css to your own project and replace the reference bulma.min.css

I will try the IconPicker extension.
